### ISSUE TITLE
Trying to create torrent with single announce url

### ISSUE THREAD

**Issue by PyR8zdl** [rndusr/torf#11]
I'm trying to create a torrent with a single announce url but I'm having issues.

`try:
        torrent = torf.Torrent(path=path,
                               trackers='https://example.com/announce/dhjhj5h4hfh4fkejfs9dhfgj0',
                               private=True,
                               comment='This is a comment',
                               piece_size=piece_size,
                               created_by='torf/3.0.0',
                               source='EXP')`

Gives this error...

`Traceback (most recent call last):
  File "/home/<REDACTED>/bin/autoup3.py", line 383, in <module>
    torrent_path = str(create_torrent(path, args.overwrite))
  File "/home/<REDACTED>/bin/autoup3.py", line 348, in create_torrent
    source='EXP')
  File "/home/<REDACTED>/env/lib/python3.6/site-packages/torf/_torrent.py", line 96, in __init__
    self.trackers = trackers
  File "/home/<REDACTED>/env/lib/python3.6/site-packages/torf/_torrent.py", line 390, in trackers
    tier = [utils.validated_url(str(item))]
  File "/home/<REDACTED>/env/lib/python3.6/site-packages/torf/_utils.py", line 47, in validated_url
    raise error.URLError(url)
torf._errors.URLError: h: Invalid URL`

The only way I can make it create a torrent successfully is to make trackers a list with the single tracker url and that adds announce-list to the torrent file.

I only want announce in the torrent file with a single url.

Am I doing this wrong?

**Comment by rndusr** [comment]
I thought the fact that I named it "trackers" (plural) would make it obvious
that a list (or some other sequence, or at least an iterable) is expected.

After a quick look at the code, it seems like the announce-list would be
empty. If that is correct, I agree that it shouldn't be added.

Out of curiosity, why don't want an announce-list in the torrent?

I should probably also check for str to be more user-friendly.

**Comment by PyR8zdl** [comment]
I'm just trying to create a torrent that is a lean as can be. And there is no sense and having announce-list if there is only one tracker.

I thought I read somewhere that if it was a str it would add a single announce and if it was a list it would make an announce-list.

Which is why I was thinking there was someting wrong with the url check since mine was a string.

But now I can't figure out where I saw that. It might have been a different project entirely.

**Comment by rndusr** [comment]
The trackers property is now really smart. Every time it is set or manipulated
it will automatically set and/or remove "announce" and "announce-list".
