### ISSUE TITLE
torrent.generate(callback, interval=1) outputs TypeError

### ISSUE THREAD

**Issue by 0-MegaMind-0** [rndusr/torf#15]
```
 def callback(torrent, filepath, pieces_done, pieces_total):
        print(f'{pieces_done / pieces_total * 100:3.0f} % done')


    torrent = Torrent(path=path, trackers='https://tracker.example.to', private=True)

    success = torrent.generate(callback, interval=1)
```
outputs a `TypeError`
```
Traceback (most recent call last):
  File "tests.py", line 16, in <module>
    success = torrent.generate(callback, interval=1)
  File "/usr/local/lib/python3.8/site-packages/torf/_torrent.py", line 972, in generate
    queue_size=threads*3)
TypeError: unsupported operand type(s) for *: 'function' and 'int'
```

I tested this with version `2.1.0` and it works fine and gives me the expected output 

```
filename.file
  1 % done
100 % done
100 % done
True

```

**Comment by rndusr** [comment]
Take a look at the arguments Torrent.generate() expects.

You need to provide the callback as a keyword argument or specify the number of threads.

I should've put the threads argument at the end, but it's too late now.

**Comment by 0-MegaMind-0** [comment]
Yup sorry for the trouble `success = torrent.generate(callback=callback, interval=1)` fixed it i was blindly following read the dos :)

**Comment by rndusr** [comment]
Oh, the error is in the docs! That's bad!

Thanks for pointing that out.
