### ISSUE TITLE
wrong infohash

### ISSUE THREAD

**Issue by ayasechan** [rndusr/torf#18]
the torrent file can download from https://nyaa.si/view/1284768

torf package version is 3.1.1

the infohash using torf is `95f3619484546e6735b0837e58d003cd0c93775f`
but the correct value is `fb8899e9faff4c0682fec40b0446cfbccbbbed18`

**Comment by ayasechan** [comment]
After modifying the `decode_value `function of the `_utils.py` file as follows, I got the correct value

```python
def decode_value(value):
    if isinstance(value, collections.abc.ByteString):
        try:
            return bytes.decode(value, encoding='utf-8', errors='strict')
        except UnicodeDecodeError:
            return value
    elif isinstance(value, collections.abc.Sequence):
        return decode_list(value)
    elif isinstance(value, collections.abc.Mapping):
        return decode_dict(value)
    else:
        return value
```

**Comment by rndusr** [comment]
Thank you for debugging this!

I made a new release with your fix.
