### ISSUE TITLE
Question remove file

### ISSUE THREAD

**Issue by romanoh** [rndusr/torf#20]
Sorry for the question as i am new to python, i work with the code:
```
t = Torrent(path=folder_path,
trackers=['https://example:2910/announce'],                                     
t.private = True
t.generate()
```
and it works, but if i want to remove the file who as an extension .nfo per example i write the `t.exclude_globs('*.nfo')`, and it gives me an error, what i am doing wrong please.

`t.exclude_globs('*.nfo')` gives an error:
maybe its not torf fault:
![imagem](https://user-images.githubusercontent.com/5342223/107847917-743d9d00-6de7-11eb-932c-61785f4118b8.png)

i get the folder path from pysimplegui, like this:
`file_path = values[1]`

the debug:
![imagem](https://user-images.githubusercontent.com/5342223/107848116-dcd94980-6de8-11eb-8c26-d3a8e22ec1e3.png)

**Comment by rndusr** [comment]
I don't understand the question.

`t.exclude_globs('*.nfo')` works but `t.exclude_globs('*.nfo')` doesn't?
Where's the difference?

And ALWAYS provide the error message. You wouldn't go to the doctor and ask for
help without explaining what's wrong.

**Comment by romanoh** [comment]
Sorry for my bad English, the `t.exclude_globs('*.nfo')` gives an error:
maybe its not torf fault:
![imagem](https://user-images.githubusercontent.com/5342223/107847917-743d9d00-6de7-11eb-932c-61785f4118b8.png)

**Comment by rndusr** [comment]
Your English is great, but your asking for help sucks. :)

Never post errors as screenshots. Just copy and paste them. And always provide
the complete error message (starting from "Traceback").

Also post the code that gives you the error, not the code that works. If I can't
reproduce the same problem you have, it's impossible for me to figure out what's
wrong.

**Comment by romanoh** [comment]
Ok, i made a new py file, eliminate everything, and use this code:
`from torf import Torrent

folder_path = "D:\\TORRENT FILE\\Before the End"
file_path = ''
# if the file path as nothing create the the torrent from folder torrent
if file_path == '':
    print('INFO-Tor: Creating Torrent...please wait')
    # Make torrent from folder
    t = Torrent(path=folder_path,
                trackers=['https://example.me:2910/announce'],
                comment='some comment '
                        'By Law')
    t.exclude_globs('*.nfo')

    t.private = True
    t.generate()`

The error is:

```
Traceback (most recent call last):
  File "D:\folder\test---2.py", line 98, in <module>
    t.exclude_globs('*.nfo')
TypeError: 'MonitoredList' object is not callable
```

**Comment by rndusr** [comment]
OK, I see what's wrong. I don't know why I didn't see that earlier.

`exclude_gobs` is not a method, it's a property. You can use it like a list.

t.exlude_globs.append('*.nfo')
t.exlude_globs.extend(['*.jpg', '*.png'])
t.exlude_globs = ['*.foo', '*.bar']

**Comment by romanoh** [comment]
Thank you.
