### ISSUE TITLE
v2 Torrent - Invalid metainfo: Missing 'pieces' in ['info']

### ISSUE THREAD

**Issue by TgSeed** [rndusr/torf#21]
Hello,
Using latest version in python.
Getting "Invalid metainfo: Missing 'pieces' in ['info']" at torrent file loading.

Example torrent file:
https://libtorrent.org/bittorrent-v2-test.torrent

**Comment by rndusr** [comment]
V2 is not supported. I might add it in the future, but it's low on my list.
