### ISSUE TITLE
Is it possible to use single file with multi-file type directory struture?

### ISSUE THREAD

**Issue by iarp** [rndusr/torf#23]
I'm not sure how to best explain this. If I supply path to a directory containing a single file, the end result is a torrent with the content matching the relative paths to the file. So the content ends up looking like, and saving like, the directory structure.

If i pass a path to a single file, no matter what name i give it, its always in the "root" of the content directory, if that makes sense. I want the single file to match the relative paths like in the multi-file.

I tried doing the following but it still includes all files
```

t = Torrent(
    path='/media/instructionals/tryer/',
    include_globs=('2015/2015-01-06_Update_23.mp4',),
    # exclude_globs=('*.mp4',),
    trackers=['https://localhost:123/announce'],
    comment='test torrent'
)
```

This ends up with the content/directory structure I want but it includes all files not just the one I've listed in include_globs. If I uncomment the exclude_globs then it complains of no files because all files are excluded.

**Comment by rndusr** [comment]
The glob patterns match against Torrent.files, which is a list of complete
relative paths within the torrent, and every item starts with the torrent's
name.

Also, if you don't want to match the start/end of the path, you need to add "*"
as a placeholder.

This should work:

    t = torf.Torrent(
        path='/media/instructionals/tryer/',
        include_globs=('*/2015/2015-01-06_Update_23.mp4',),
        exclude_globs=('*.mp4',),
    )

You can also use regular expressions if you prefer to explicitly specify the
begining/end:

    t = torf.Torrent(
        path='/media/instructionals/tryer/',
        include_regexs=(r'2015/2015-01-06_Update_23\.mp4$',),
        exclude_regexs=(r'\.mp4$',),
    )

Hope that helps.

**Comment by iarp** [comment]
That did it thanks. After a bit more digging and research I think I've realized I cannot do what I was hoping to achieve. 

Years ago a company put out some videos on torrent and the name within the torrent client was like `Company Name E01 Exercise 1` and the directory structure within the torrent was `Company/2016/E01 Exercise 1.mp4` so that when you would download 6 torrent files (for 6 episodes) and the end result was all files ended up in a neatly layed out directory structure that didn't need to copy/rename/move files..etc.

That's what I'm trying to achieve and after some more googling it sounds like the directory name and torrent name are enforced.

**Comment by rndusr** [comment]
The structure of a torrent file is actually pretty simple and should make it
obvious what is possible and what isn't. Check out the "info dictionary" section
here: https://www.bittorrent.org/beps/bep_0003.html

In your working example, were you using a special torrent client? Because for
any client I know, if you download a torrent that creates "Company/2016/E01
Exercise 1.mp4", the torrent would have to be named "Company", i.e. that would
be what the client displays in the torrent list.

**Comment by iarp** [comment]
It's been a long time since. Thanks for you help and the information!
