### ISSUE TITLE
Missing __enter and __exit method

### ISSUE THREAD

**Issue by belatedluck** [rndusr/torf#25]
__enter and __exit method are missed in class Torrent, and 'with' cannot be used.
code:
with Torrent(....) as t:
----....
----t.write()
I got an error:
AttributeError: \_\_enter\_\_

**Comment by rndusr** [comment]
What should `__enter__()` and `__exit__()` do?

**Comment by belatedluck** [comment]
> 
These methods are used in Context Manager.
__enter__ is used to creates context and __exit__ cleans it. Additionally, __exit__ may help when an exception occurs.
Ref: [https://book.pythontips.com/en/latest/context_managers.html](https://book.pythontips.com/en/latest/context_managers.html)

**Comment by nikow** [comment]
Most likely that person wants to use Torrent class as "open" in python, so you can write `with Torrent() as t:`, set the details and have them saved at exit.

**Comment by rndusr** [comment]
OK, thanks for helping out.

But I don't see the point. The Torrent class never opens any file. If you want
to write the torrent to a file, you use the write() method.

**Comment by rndusr** [comment]
But `__enter__()` and `__exit__()` are still just functions that are called by
the `with` block. If they don't do anything, calling them is pointless.

So my question remains: What should `__enter__()` and `__exit__()` do? Or in
other words: What is the point of using `Torrent` as a context manager?

**Comment by belatedluck** [comment]
> 

Thanks for your response. I think not everyone knows that Torrent only opens a file in the write() method and they may try to use `with`. And then, there will be errors when they run the program. Adding `__enter__` and `__exit__` does not make any difference for the torf itself, but it will help to avoid a meaningless error debuging. This is my case. Thanks for your effort.

**Comment by rndusr** [comment]
If you can't be bothered to read the documentation, you absolutely *should* run into errors.

**Comment by belatedluck** [comment]
Well, never mind. I read the docs and the codes, and I'm able to use it correctly now. This is just a suggestion to make torf easier to use, in my personal opinion. If you think there is no need to do so, just forget it.
