### ISSUE TITLE
Is it possible to add a file with a different filename inside the torrent?

### ISSUE THREAD

**Issue by wwww-wwww** [rndusr/torf#27]
For example, I have a file named "out.html" and want it to be named "index.html" inside the torrent file.
I am loading the paths by setting filepaths, so I figured it could be possible to either have it when setting or change it after under metainfo["info"]["files"].

**Comment by rndusr** [comment]
Maybe.

Try calling generate() first while you still have "out.html" in the metainfo,
then rename it to "index.html".

**Comment by wwww-wwww** [comment]
write with validate=True complains about the missing file
write with validate=False has it with the original filename

**Comment by rndusr** [comment]
What I meant was something like this:

    torrent.generate()
    torrent.metainfo["info"]["files"][0]["path"] = ["index.html"]

Can you post your code?

**Comment by rndusr** [comment]
OP seems to have lost interest.
