### ISSUE TITLE
infohash got changed after load, without any modification

### ISSUE THREAD

**Issue by zero-custom** [rndusr/torf#31]
torrent file's infohash got change after load, found at least 2 torrent file.

test code:
```
import torf

t = print(torf.Torrent.read('/config/torrents/sample1.torrent'))
print(t.infohash)
```

result:
![QQ截图20230911131425](https://github.com/rndusr/torf/assets/22925474/0ce4f999-52d4-4338-a7fa-85378bf3da3b)

[sample.zip](https://github.com/rndusr/torf/files/12572397/sample.zip)

**Comment by rndusr** [comment]
Thanks for reporting this.

Should be fixed in the latest release.

Also, please never ever post screenshots of text anywhere. You can't copy&paste
it and it's not accessible (blind people can't use text-to-speech software).
