### ISSUE TITLE
`collections.abc.ByteString` is deprecated in Python 3.12 and will be removed in Python 3.14

### ISSUE THREAD

**Issue by jwodder** [rndusr/torf#34]
This library makes use of [`collections.abc.ByteString`](https://docs.python.org/3/library/collections.abc.html#collections.abc.ByteString) in several locations, but this type has been deprecated (and produces a warning) in Python 3.12 and is slated for removal in Python 3.14.  See the link for advice on how to replace it.

**Comment by rndusr** [comment]
Thanks for the heads up!

The latest release uses `bytes` instead.
