### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [rndusr/torf#36]
Hi,
Might you consider switching back to MIT or switching to LGPL so we can use this as a package?
Thank you!

**Comment by rndusr** [comment]
Thank you for asking, but torf has always been GPL and it always will be.

Who is "we" and why can't you package GPL software?

**Comment by fakerybakery** [comment]
Hi, thanks for your reply.
1. According to the git history the license was originally MIT but changed to GPL
2. I am not affiliated with any organization interested in using this software, but simply would not like my scripts using this package to have to be GPL'd as well.

**Comment by rndusr** [comment]
Oh, ok. That MIT license must be way, way back from when I forked dottorrent.

But there's no code left from dottorrent, so you're out of luck. dottorrent
itself is still MIT, though.

**Comment by fakerybakery** [comment]
OK, thank you for the information.
