### ISSUE TITLE
Create single file torrent from a stream

### ISSUE THREAD

**Issue by dbnicholson** [rndusr/torf#37]
I'm creating single file torrents for large files, and the files are stored on a remote server (an S3 bucket). Rather than downloading the large file and requiring the disk space for it, I'd like to be able to stream the content directly into the generator. Is that possible? It almost looked possible to me reading through the internals, but at the end of the day it seems like the exposed interface really expects a file on disk.

Ideally it would be great to do this for a multi-file torrent, but that would understandably be more difficult.

**Comment by rndusr** [comment]
Sounds to me like you want something like sshfs? You mount your S3 bucket to a
local directory and SSH transparently transmits any file system operations over
a secure connection to/from the bucket.

**Comment by dbnicholson** [comment]
Those do exist (s3fs-fuse, goofys) and we do use them. That is my fallback plan. However, I'm hoping that since the entire operation is just to break the stream into chunks and hash them (something torf already does), that I can just tell torf the filename and size and let it do the hashing. I could certainly open code that and manually set `pieces`, but I'd much rather have torf do it since it already knows how to handle the edge cases.

**Comment by dbnicholson** [comment]
The file system is an extra thing to handle and potentially go wrong. Is FUSE available? Will the mount and unmount succeed? Can you properly clean up in case of errors?

Obviously the content stream would need to be provided, but you can get that from the network. S3 is just HTTP under the hood. You can provide torf the name, size and an opened stream from an HTTP response. The same thing it does when opening the file from the file system. It's exactly how the above FUSE filesystems are able to present the remote objects as files.

**Comment by rndusr** [comment]
Well, it's an interesting idea to make all the file system conveniences
optional. But it's not something I had in mind when I wrote torf, and I don't
see an easy way of adding that feature.

I also don't really understand why you don't want to use one of the established
network file systems. Solving the same issue again for torf specifically would
be lots of work and it would never be as tried and tested. And then there's even
more work and room for bugs on the user side where file name, size and data is
generated.
