### ISSUE TITLE
Allow creating 64 MB piece size

### ISSUE THREAD

**Issue by Pentaphon** [rndusr/torf#38]
I realize that 32MB piece size support was added recently but it seems the new piece size support standard for most clients currently in use is 64MB.

- qBittorrent supports 64MB pieces and larger (and will create up to to 256MB piece sizes in https://github.com/qbittorrent/qBittorrent/pull/19535)

- Transmission 4.0 supports up to 64MB pieces (as shown in https://github.com/transmission/transmission/pull/3768)

- Deluge supports 64 MB piece size torrents

- BiglyBT supports 64 MB piece size torrents. 

- https://github.com/kz26/dottorrent already supported creation of 64MB but that ability was lost in torf. 

- py3createtorrent recently went to 64 MB in https://github.com/rsnitsch/py3createtorrent/issues/34

- uTorrent 3.x supports 64MB piece size torrents

- Tixati 3.x supports 64MB piece size torrents as of https://forum.tixati.com/support/7137

That's all the major clients in use today. 

Please allow us to keep up with these clients by giving us the ability to create 64MB piece size torrents. That should be sufficient for years to come as torrents keep getting bigger and bigger.

**Comment by rndusr** [comment]
Piece size is already unlimited. Just set Torrent.piece_size_max_default to 64
TiB or whatever you like. Just tested it with 128 MiB and it works.

What exactly is your issue?

**Comment by Pentaphon** [comment]
> What exactly is your issue?

Sorry, I just wanted to make sure this was not getting in the way of torf-gui doing it, which I use. Closing this. Thanks.
