### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by Ridente** [rndusr/torf#39]
Hello

I usually create a torrent with Torf that  includes a folder with all the files inside. How do I create a torrent with subfolders and their respective files as well?

I tried with 'include_globs,' but it keeps creating a torrent with all the files excluding those from the subfolders.

for example:
```
torf.Torrent(path="/home/ridente/FolderA/")
```

```
FolderA
     hello_1.mkv
     hello_2.mkv
     FolderB
           hello_3.mkv
     FolderC
           hello_4.mkv
```
It will create a torrent with only 'hello_1.mkv' and 'hello_2.mkv' without including FolderB and FolderC (subfolders and files)

Thank you

**Comment by rndusr** [comment]
Works for me.

Are there any exclude options in your ~/.config/torf/config?

Maybe FolderB/C are dead links, unreadable, empty or something?

**Comment by Ridente** [comment]
Sry I have no Tor configuration, but it's working perfectly... It was my mistake...
My Python code was pointing to a file, not a folder

 Thank you
