### ISSUE TITLE
Installing with `python ./setup.py --root=` makes `$prefix/usr/lib/python3.6/site-packages/torf-1.3-py3.6.egg-info/*` have 0700 permissions.

### ISSUE THREAD

**Issue by doronbehar** [rndusr/torf#4]
As the title suggests, from some reason, when I try to run the install script `setup.py`, I get `-rw------` permissions on the egg-info folder of `torf`.

It doesn't happen so while installing with `pip --root <>`. Any idea why this is happening?

**Comment by rndusr** [comment]
Shouldn't it be `python ./setup.py install --root=`?

Otherwise, no idea, sorry. I know practically nothing about python packaging.

If it works, why don't you use pip?

**Comment by rndusr** [comment]
It looks like it depends on the current `umask`.

    $ umask 000
    $ python3 setup.py build
    [...]
    $ python3 setup.py install --root="./test" --optimize=1 --skip-build
    [...]
    $ ls -la test/usr/local/lib/python3.6/dist-packages/torf
    total 68K
    drwxrwxrwx 3 ich ich 4.0K May  4 12:24 ./
    drwxrwxrwx 4 ich ich 4.0K May  4 12:24 ../
    -rw-rw-rw- 1 ich ich 3.3K Jan 13 17:18 _errors.py
    -rw-rw-rw- 1 ich ich 1.2K Jan  2 17:42 __init__.py
    drwxrwxrwx 2 ich ich 4.0K May  4 12:24 __pycache__/
    -rw-rw-rw- 1 ich ich  34K Apr  7 19:33 _torrent.py
    -rw-rw-rw- 1 ich ich 7.4K Jan 13 17:18 _utils.py
    -rw-rw-rw- 1 ich ich   20 Apr  7 16:05 _version.py

If I run `umask 007` before, I get the same result with `-rw-rw----`.

**Comment by rndusr** [comment]
I'm closing this as it doesn't seem to concern torf.

**Comment by doronbehar** [comment]
Sorry for the delayed response. Well first of all, as for your last comment I'm talking about the egg-info directory, not the main directory where all the `.py` files are located.

Besides, I've investigated the subject a little further and I've learned that the `setup.py` script copies the contents of a directory called `torf_cli.egg-info` residing in the source directory, probably created during the build process. Since the files in this directory have `-rw------` permissions, no matter what the `umask` is. Therefor, copying these files as they are to the appropriate location specified with `--root` when running `python setup.py` makes them unreadable by non-root users, without `umask` having any influence.

According to this comment: https://github.com/PyTables/PyTables/issues/488#issuecomment-136289511 perhaps you just need to upload a new version and it will be fixed.

**Comment by rndusr** [comment]
Thanks for researching. But I still don't see how this can be fixed in torf.

> I'm talking about the egg-info directory, not the main directory where all the
> `.py` files are located.

The files in `usr/local/lib/python3.6/dist-packages/torf-1.3.egg-info/` are also
affected by `umask`. At least for me.

The pkgbuild for another project of mine seems to work fine, and the relevant
parts of `setup.py` are pretty much identical.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=stig

**Comment by doronbehar** [comment]
Yea, I use the AUR package `stig` myself as well. I wonder why this is happening, we'll see if it will appear on your next release. In the meanwhile I added `chmod -R a+rX ${pkgdir}` on `python-torf`'s `PKGBUILD`.

**Comment by doronbehar** [comment]
Well first of all the same issue happened to me with `torf-cli` which this package is it's dependency. Perhaps the difference between my setup and yours is that I use as the source a tar file from `https://files.pythonhosted.org/packages/source/`. Source tarballs from there include from some reason the `torf-1.3.egg-info` directory which has the bad permissions.

I've ran the same commands with the tar file from the GitHub release and it works like a charm, without touching `umask`. Thanks for helping me debug this! I'll update the `PKGBUILD`s of your AUR packages accordingly.

**Comment by rndusr** [comment]
Aha! The stig pkgbuild uses the tar file from github, not from pypi. That's the
difference! The git repo doesn't track the egg-info dir, so it's created with
`python setup.py build`.
