### ISSUE TITLE
Exclude tests directory

### ISSUE THREAD

**Issue by D3vil0p3r** [rndusr/torf#42]
Currently, by installing torf, it creates `/usr/lib/python3.12/site-packages/tests` directory that can cause conflicts with other Python libs.

Can you please exclude `tests*` by `pyproject.toml` file?

It can be fixed by: https://github.com/rndusr/torf/pull/43

If you agree, after merge, can you please release an updated minor version on PyPi?

**Comment by rndusr** [comment]
Should be fixed: https://github.com/rndusr/torf/commit/56d89f0b6c1a9f8e46ea0131302411d72c24acc0
