### ISSUE TITLE
Question about handling filepaths

### ISSUE THREAD

**Issue by jessielw** [rndusr/torf#45]
I have read over and tested the documentation when it comes to include/exclude globs/regexs. While I can achieve my goal utilizing these, is it possible to just directly modify the included filepaths/files to only include things that I want when it comes to a `directory`. 

Structure: 
```
folder_a
    file.mkv
    file.srt
    file.log
    subfolder_a
         file.h264
```

Let's say I want to use torf to open `folder_a` and I know that I only want to include `folder_a/` `file.mkv` and `file.srt`. Could I directly modify `filepaths` and/or `files` to only include that in the final output? Utilizing the globs/regexs feel like it could be error prone in certain situations when i know specifically before hand what files I'd like to have (say selecting from a filetree or something such as that).

**Comment by rndusr** [comment]
Yes, you should be able to set or modify `files` (relative filepaths specified in the torrent) or `filepaths` (filepaths that exist in your file system) and torf should figure out what you mean and if it makes sense.

At least that was my idea. This is a pretty messy and probably not widely used feature, so I'd expect bugs.

**Comment by jessielw** [comment]
I was mostly just wondering if it was possible and setup for that. This is an edge case and not something that most/if any users would utilize since it's very uncommon to see it. I'll likely just use it the traditional way and not mess around with things to avoid bugs. 

Thanks for the response!
