### ISSUE TITLE
metadata mismatch in pyproject.toml

### ISSUE THREAD

**Issue by Ravencentric** [rndusr/torf#50]
The trove classifiers indicate support for 3.8+ but the [`requires-python`](https://github.com/rndusr/torf/blob/25280d28d50cdb907a7e5cb670c863b6fdaf1026/pyproject.toml#L24) indicates 3.7+.  The former is merely metadata while the latter actually affects downloaders. Python 3.8 also reached end of life last week (https://endoflife.date/python) so it might be time to drop it and fix the metadata consistency.

**Comment by rndusr** [comment]
Nice catch.

I'll keep 3.8 supported until there is a reason not to.
Might make things easier for some users.
