### ISSUE TITLE
Help,How to seed these files?

### ISSUE THREAD

**Issue by makelove** [rndusr/torf#7]
After create a torrent file ,How to seed these files ?

use what kind of software ?

Can python handle it ?
with some code

**Comment by rndusr** [comment]
You need a BitTorrent client: https://en.wikipedia.org/wiki/Bittorrent

These are some popular clients:
https://transmissionbt.com/
https://deluge-torrent.org/
https://rakshasa.github.io/rtorrent/

You start the client and give it the torrent file.

The torrent file tells the client which files to download and where to find
peers.

The client will then connect to peers and share the files that are specified in
the .torrent file.

**Comment by makelove** [comment]
can I write some python code to do this seeding job ?

**Comment by rndusr** [comment]
No.

You'd have to write your own BitTorrent client, and managing communication with
trackers, DHT and peers, file system access, load balancing, etc is fairly
complex and offers lots and lots of room for bugs that will only manifest after
years of usage.

You need to run a BitTorrent client or your .torrent files are worthless.

**Comment by makelove** [comment]
OK, Thank you
