### ISSUE TITLE
Parse magnet link?

### ISSUE THREAD

**Issue by dausruddin** [rndusr/torf#9]
Hi. I believe this module doesn't support magnet link parsing? Is it possible for you to implement it in the future?

Thanks

**Comment by rndusr** [comment]
Great idea. I don't know why I haven't thought of that myself.

**Comment by dausruddin** [comment]
Really? 😅
I'll be waiting then.
Thank you😁😁

**Comment by rndusr** [comment]
I've added a Magnet class with a from_string() class method and a as_torrent()
method that returns a Torrent instance.

**Comment by dausruddin** [comment]
Thanks a lot!

**Comment by dausruddin** [comment]
Can you make a release on pip?

**Comment by rndusr** [comment]
Yes, as soon as it's ready.
